"""The SymPy backend: computer algebra (ARCHITECTURE.md §3.7).

Arguments are converted with ``to_sympy`` before calling SymPy, and
results with ``from_sympy`` afterwards, so exact numbers come back as
ER2 ``Integer`` and ``Rational``.  Symbolic expressions stay SymPy
objects (D11).
"""

import functools

import sympy

from er2.runtime.numbers import Integer, Rational

__all__ = [
    "cancel",
    "charpoly",
    "collect",
    "det",
    "diff",
    "discriminant",
    "echelon_form",
    "expand",
    "factor",
    "factorial",
    "from_sympy",
    "gcd",
    "groebner",
    "integrate",
    "inverse",
    "isirreducible",
    "kernel",
    "lcm",
    "limit",
    "minimal_polynomial",
    "rank",
    "reduce_polynomial",
    "resultant",
    "generating_function",
    "series",
    "simplify",
    "solve",
    "solve_linear",
    "to_sympy",
]


def to_sympy(obj):
    """Convert ER2 numbers in ``obj`` (and in its containers) to SymPy."""
    if isinstance(obj, bool):
        return obj
    if isinstance(obj, int):
        return sympy.Integer(int(obj))
    if isinstance(obj, Rational):
        return sympy.Rational(obj.numerator, obj.denominator)
    if isinstance(obj, (list, tuple, set, frozenset)):
        return type(obj)(map(to_sympy, obj))
    if isinstance(obj, dict):
        return {to_sympy(k): to_sympy(v) for k, v in obj.items()}
    return obj


def from_sympy(obj):
    """Convert SymPy numbers in ``obj`` (and in its containers) to ER2.

    ``sympy.Integer`` becomes ``Integer`` and ``sympy.Rational`` becomes
    ``Rational``; other SymPy objects are returned unchanged.
    """
    if isinstance(obj, sympy.Integer):
        return Integer(int(obj))
    if isinstance(obj, sympy.Rational):
        return Rational(int(obj.p), int(obj.q))
    if isinstance(obj, (list, tuple, set, frozenset)):
        return type(obj)(map(from_sympy, obj))
    if isinstance(obj, dict):
        return {from_sympy(k): from_sympy(v) for k, v in obj.items()}
    return obj


def _boundary(function):
    """Wrap a SymPy function with the ER2 conversions."""

    @functools.wraps(function)
    def wrapper(*args, **kwargs):
        args = [to_sympy(arg) for arg in args]
        kwargs = {key: to_sympy(value) for key, value in kwargs.items()}
        return from_sympy(function(*args, **kwargs))

    return wrapper


expand = _boundary(sympy.expand)
factor = _boundary(sympy.factor)
simplify = _boundary(sympy.simplify)
collect = _boundary(sympy.collect)
cancel = _boundary(sympy.cancel)
diff = _boundary(sympy.diff)
integrate = _boundary(sympy.integrate)
limit = _boundary(sympy.limit)
solve = _boundary(sympy.solve)
series = _boundary(sympy.series)
gcd = _boundary(sympy.gcd)
lcm = _boundary(sympy.lcm)
factorial = _boundary(sympy.factorial)
minimal_polynomial = _boundary(sympy.minimal_polynomial)


# Linear algebra (M5, D12): SymPy's matrix methods, for the matrices that
# ``dispatch`` does not send to PARI (symbolic or floating-point entries).


@_boundary
def det(matrix):
    """Return the determinant of a square matrix."""
    return matrix.det()


def inverse(matrix):
    """Return the inverse of a square matrix."""
    return matrix.inv()


def rank(matrix):
    """Return the rank of a matrix."""
    return Integer(matrix.rank())


def kernel(matrix):
    """Return a basis of ``{v : matrix * v = 0}`` as column matrices."""
    return matrix.nullspace()


def charpoly(matrix, var):
    """Return the characteristic polynomial ``det(var*I - matrix)``."""
    return matrix.charpoly(var).as_expr()


def echelon_form(matrix):
    """Return the reduced row echelon form of a matrix."""
    return matrix.rref()[0]


def solve_linear(matrix, rhs):
    """Return the solution ``v`` of ``matrix * v = rhs``."""
    return matrix.solve(rhs)


def resultant(f, g, var):
    """Return the resultant of ``f`` and ``g`` in ``var``.

    ``sympy.resultant`` puts the polynomial of higher degree first
    without the sign that swapping the arguments costs, so it answers
    ``Res(g, f)`` when ``deg f < deg g``.  ER2 follows the standard
    definition, PARI's (ARCHITECTURE §3.4), so the sign is put back:
    ``Res(f, g) = (-1)^(deg f * deg g) * Res(g, f)``.
    """
    f, g = sympy.Poly(f, var), sympy.Poly(g, var)
    degrees = f.degree() * g.degree()
    result = f.resultant(g)
    if f.degree() < g.degree() and degrees % 2:
        result = -result
    return from_sympy(result)


def discriminant(f, var):
    """Return the discriminant of ``f`` in ``var``.

    SymPy's own sign convention here is PARI's: the discriminant is
    ``Res(f, f')`` with ``deg f' = deg f - 1``, so one of the two
    degrees is even and swapping the arguments costs no sign.
    """
    return from_sympy(sympy.discriminant(to_sympy(f), var))


def groebner(seq, *gens, **options):
    """Return a Gröbner basis of the ideal generated by ``seq``.

    PARI has no Gröbner bases, so this is always SymPy's.  The result is
    SymPy's ``GroebnerBasis``, which ER2's printer already writes in
    ``^`` notation because it prints the basis through ``_print_Add``.
    """
    return _boundary(sympy.groebner)(seq, *gens, **options)


def reduce_polynomial(f, basis, *gens, **options):
    """Return the remainder of ``f`` modulo ``basis``.

    A ``GroebnerBasis`` carries its own generators and monomial order,
    so ``gens`` and ``options`` are only used for a plain list.
    """
    f = to_sympy(f)
    if isinstance(basis, sympy.GroebnerBasis):
        return from_sympy(basis.reduce(f)[1])
    remainder = sympy.reduced(f, to_sympy(basis), *gens, **options)[1]
    return from_sympy(remainder)


def isirreducible(expr, modulus=None, **options):
    """Whether a polynomial is irreducible (SymPy's ``Poly``)."""
    if modulus is not None:
        options["modulus"] = modulus
    return bool(sympy.Poly(expr, **options).is_irreducible)


def generating_function(coefficients, var, exponential=False):
    """Build the truncated generating function of a sequence.

    The ordinary generating function is ``sum a_n x^n``; with
    ``exponential=True`` it is ``sum a_n x^n / n!``.  Pure SymPy: this
    is construction, not computation, so there is nothing for PARI to
    do (M6 task 5).
    """
    terms = list(coefficients)
    body = sympy.S.Zero
    for n, a in enumerate(terms):
        term = sympy.sympify(a) * var**n
        if exponential:
            term = term / sympy.factorial(n)
        body = body + term
    return sympy.expand(body) + sympy.O(var ** len(terms))
